import { mkdir, readFile, writeFile } from "node:fs/promises";
import { argv } from "node:process";
import { pathToFileURL } from "node:url";

const outputFile = new URL("./data.generated.mjs", import.meta.url);
const sampleModuleDirectory = new URL("./data/", import.meta.url);
const identifierFor = (id) => id.replace(/-([a-z])/gu, (_, letter) => letter.toUpperCase());
const VERSION_ORDER = ["original", "a", "b", "c"];
const versionMetadata = Object.freeze({
  original: { short: "Original", label: "Original" },
  a: { short: "A", label: "Humanize Korean" },
  b: { short: "B", label: "i-have-adhd" },
  c: { short: "C", label: "Say It Straight" }
});
const sampleDefinitions = [
  { id: "release-note", label: "주간 배포 안내", description: "제목, 문단, 목록" },
  { id: "meeting-followup", label: "회의 후속 메모", description: "체크박스, 담당자, 기한" },
  { id: "incident-review", label: "장애 회고", description: "타임라인 표, 인용, 지표" },
  { id: "support-reply", label: "고객 지원 답변", description: "문단, 순서 목록" },
  { id: "internal-proposal", label: "내부 제안서", description: "장단점, 표" },
  { id: "api-migration", label: "API 전환 안내", description: "코드, 경고, 링크" },
  { id: "release-note-en", label: "Deployment notice", description: "Heading, paragraphs, list" },
  { id: "meeting-followup-en", label: "Meeting follow-up", description: "Checkboxes, owners, due dates" },
  { id: "incident-review-en", label: "Incident review", description: "Timeline table, quote, metrics" },
  { id: "support-reply-en", label: "Support reply", description: "Paragraphs, ordered list" },
  { id: "internal-proposal-en", label: "Internal proposal", description: "Benefits, costs table" },
  { id: "api-migration-en", label: "API migration", description: "Code, warning, links" }
];
function metricsFor(text) {
  return {
    characters: text.length,
    words: text.match(/\S+/gu)?.length ?? 0,
    lines: text === "" ? 0 : text.split(/\r?\n/u).length - (text.endsWith("\n") ? 1 : 0)
  };
}

async function buildSample(definition) {
  const versions = {};
  for (const versionId of VERSION_ORDER) {
    // A sample may omit a version whose treatment does not apply to it —
    // English samples have no Humanize Korean variant. The selector renders
    // the gap as a disabled "Unavailable" option.
    let text;
    try {
      // Normalise newlines: a Windows checkout yields CRLF, which would change
      // both the embedded text and its metrics against the committed modules.
      text = (await readFile(new URL(`../samples/${definition.id}/${versionId}.md`, import.meta.url), "utf8"))
        .replace(/\r\n/gu, "\n");
    } catch (error) {
      if (error.code === "ENOENT") continue;
      throw error;
    }
    versions[versionId] = {
      id: versionId,
      ...versionMetadata[versionId],
      text,
      metrics: metricsFor(text),
      audits: []
    };
  }
  return { ...definition, versions };
}

export async function buildSamples() {
  return Object.fromEntries(await Promise.all(sampleDefinitions.map(async (definition) => [definition.id, await buildSample(definition)])));
}

export const SAMPLE_IDS = sampleDefinitions.map(({ id }) => id);

async function buildData() {
  const samples = await Promise.all(sampleDefinitions.map(async (definition) => [definition.id, await buildSample(definition)]));

  // One module per sample rather than a single blob: each stays small enough to
  // review on its own, and editing one sample produces a one-file diff.
  await mkdir(sampleModuleDirectory, { recursive: true });
  for (const [id, sample] of samples) {
    await writeFile(
      new URL(`./${id}.mjs`, sampleModuleDirectory),
      `export const sample = Object.freeze(${JSON.stringify(sample, null, 2)});\n`,
      "utf8"
    );
  }

  const ids = sampleDefinitions.map(({ id }) => id);
  const index = [
    "// Generated by build-data.mjs. Run `node build-data.mjs` after editing samples/.",
    ...ids.map((id) => `import { sample as ${identifierFor(id)} } from "./data/${id}.mjs";`),
    "",
    `export const SAMPLE_ORDER = ${JSON.stringify(ids)};`,
    "",
    `export const VERSION_ORDER = ${JSON.stringify(VERSION_ORDER)};`,
    "",
    "export const SAMPLES = Object.freeze({",
    ...ids.map((id) => `  "${id}": ${identifierFor(id)},`),
    "});",
    ""
  ].join("\n");

  await writeFile(outputFile, index, "utf8");
}

// Importing this module must not write files; the staleness test imports it.
if (argv[1] && import.meta.url === pathToFileURL(argv[1]).href) await buildData();
