export function helpText() {
  return [
    "Usage:",
    "  superloopy loop begin --brief TEXT [--mode light|strict] [--session-id ID] [--force]",
    "  superloopy loop create --brief TEXT [--mode light|strict] [--session-id ID] [--force]",
    "  superloopy loop next [--session-id ID] [--json]",
    "  superloopy loop guide [--session-id ID] [--json]",
    "  superloopy loop trace [--session-id ID] [--json]",
    "  superloopy loop report [--artifact PATH] [--session-id ID] [--json]",
    "  superloopy loop check [--session-id ID] [--json]",
    "  superloopy loop evidence --goal-id ID --criterion-id ID --status pass|fail|blocked --artifact PATH [--notes TEXT] [--session-id ID]",
    "  superloopy loop capture --goal-id ID --criterion-id ID [--artifact PATH] [--notes TEXT] [--session-id ID] -- COMMAND [ARGS...]",
    "  superloopy loop prove [--artifact PATH] [--notes TEXT] [--session-id ID] -- COMMAND [ARGS...]",
    "  superloopy loop review --status passed --artifact PATH.json [--notes TEXT] [--session-id ID]",
    "  superloopy loop checkpoint --goal-id ID --status complete|failed|blocked --evidence TEXT [--quality-gate PATH] [--session-id ID]",
    "  superloopy loop finish [--evidence TEXT] [--artifact PATH.json] [--notes TEXT] [--session-id ID]",
    "  superloopy loop handoff --agent NAME --assignment TEXT [--status TEXT] [--verdict TEXT] [--artifact PATH] [--language TAG] [--session-id ID] [--json]",
    "  superloopy loop fleet [--language TAG] [--session-id ID] [--json]",
    "  superloopy loop status [--session-id ID] [--json]",
    "  superloopy loop bind --confirm-current-root [--session-id ID] [--json]   # bind a legacy plan to this worktree",
    "  superloopy loop trust [--session-id ID] [--json]   # approve plan commands for audit re-run (plans that arrived with the repo)",
    "  superloopy agents install [--target PATH] [--force] [--json]",
    "",
    "Quick flow:",
    "  superloopy loop begin --brief \"Ship the task\" --json",
    "  superloopy loop prove -- <validation-command>",
    "  superloopy loop check",
    "  superloopy loop finish --evidence \"criteria passed\" --artifact .superloopy/evidence/gate.json --json",
    "",
    "Evidence rule:",
    "  Pass evidence must be a non-empty artifact under the active evidence root.",
    "  Quality gate artifacts are JSON; use loop report or worker evidence for Markdown reports.",
    "  Run `superloopy loop guide --json` anytime to get the exact next action and proof target.",
    ""
  ].join("\n");
}
